### ISSUE TITLE
Consider migrating the developer space of AWMD stats from Github to Gerrit

### ISSUE THREAD

**Issue by ch3nkula** [samuelguebo/awmd-stats#12]
This will enable future contributors to this tool to use Wikimedia practices to contribute to Wikimedia related projects. Since Github is not used by Wikimedia for development, it would be great to follow WM practices.

* This issue will entail that we request a Gerrit repo for the tool via Wiki here: https://www.mediawiki.org/wiki/Gerrit/New_repositories/Requests. Once it's approved, we would would then migrate everything to Gerrit and continue development there.

* Also, we would no longer use Github to file issues, any issues related to the tool will be moved over to the AWMD phabricator work board.

**Comment by ch3nkula** [comment]
@samuelguebo, I think you should consider working on this? Let's move to Gerrit and enforce the SDLC practices, what do you think?

**Comment by samuelguebo** [comment]
@ch3nkula, I think it is about time to do that. I just filed a new request: https://www.mediawiki.org/wiki/Gerrit/New_repositories/Requests

**Comment by ch3nkula** [comment]
Okay, maybe you should add me as CR+2 too but like you want? :) So I can help in CR+2?

**Comment by xSavitar** [comment]
And this can be marked as resolved as it's been done. Thanks for working on this @samuelguebo 👍
