### ISSUE TITLE
Rank users contributions (for a month) on dashboard

### ISSUE THREAD

**Issue by ch3nkula** [samuelguebo/awmd-stats#13]
* For now, let's just rank user contributions on highest number of patches submitted, even if the patches are not merged, under review or are abandoned (as this will still need to be calculated manually to be ranked on the phabricator leader board ticket).

* But in the future, we would want to rank the user contributions based on an algorithm that does the manual ranking for us automatically, the algorithm should be intelligent enough to do the ranking that will just be copy pasted into phabricator.

**Comment by xSavitar** [comment]
Imported on phab as https://phabricator.wikimedia.org/T202232, closing this now!
