### ISSUE TITLE
Expand awmd-stats tool for use by other event organizers in the Wikimedia movement

### ISSUE THREAD

**Issue by srish** [samuelguebo/awmd-stats#28]
I met event organizers of the Women Tech storm hackathon who are exploring ways to retain/track candidates from their events. After having a chat with them and being reminded of your tool again at Wikimania, I was wondering if we could expand this tool so that other event organizers in the movement could use it in a similar way like with the AWMD initiative. 

Not quite sure if this is a good idea, thoughts welcome! :) 

But, if it is, then maybe we could consider creating a Phabricator ticket, see what others think about this idea and probably this task could become a good candidate for Wikimedia outreach programs?

**Comment by ch3nkula** [comment]
@srish, the tool can obviously be expanded, we shouldn't limit it to this level, a task to track this if epic :)

**Comment by xSavitar** [comment]
@srish, imported on phab as https://phabricator.wikimedia.org/T202233. Closing this now!
