### ISSUE TITLE
Export or Move all Github Issues of this project to Phabricator Tasks on AWMD workboard

### ISSUE THREAD

**Issue by ch3nkula** [samuelguebo/awmd-stats#33]
After a Gerrit repo has been created, all issues, currently #28, #15, #13, #11, #2 should be moved to Phabricator work board of AWMD project. This will track this and once this is done, the repo can be deleted or archived then things continue on Gerrit as usual. @samuelguebo, do you think this is a good idea?

**Comment by xSavitar** [comment]
@samuelguebo, all issues imported on our phab work board, you can see it under the column `awmd-stats-tool (Tasks)`. You can archive here as soon as you're ready :)

**Comment by samuelguebo** [comment]
@ch3nkula, you did really great importing those issues to Phabricator.
